### ISSUE TITLE
Security Patch

### ISSUE THREAD

**Issue by aarslan007** [boydaihungst/treble_build_derpfest#1]
Hi, I've been trying to contact you for some time now. I'm using your Android 14 Evolution X GSI. Most of the things are working fine in the ROM, but the Security Patch is September 2022. Is that intentional? Can you please fix it?

**Comment by aarslan007** [comment]
Could you enable the Issues tab in the Evolution X page as well? I have some feedback that might be helpful for you.

**Comment by boydaihungst** [comment]
That is vendor security patch. Not system. So don't be worried.

**Comment by aarslan007** [comment]
It's the Android Security Patch. Check About Device > Android Version > Android Security Update. It's September 5, 2022.

**Comment by aarslan007** [comment]
> That is vendor security patch. Not system. So don't be worried.

It's the Android Security Patch. Check About Device > Android Version > Android Security Update. It's September 5, 2022.

**Comment by boydaihungst** [comment]
Yes I know. My is june 2023. That's vendor security. A little tricky way to bypass CTS. That is just a text doesn't effect any else.

**Comment by aarslan007** [comment]
Thanks. 🙂
