### ISSUE TITLE
What might be the reason behind my device's random reboot occurring every 5 minutes?

### ISSUE THREAD

**Issue by XNEOFF** [boydaihungst/treble_build_derpfest#10]
**_Why does my Samsung A30s frequently reboot every 5 minutes? Also, what causes significant UI lagging, and why is the GSI (Generic System Image) instability on my device?_**

**Comment by boydaihungst** [comment]
I'm not alien how the hell do I know your issue with logs?

**Comment by boydaihungst** [comment]
Only supported 4.14+.

**Comment by XNEOFF** [comment]
Kernel is 4.4 and 4.1.4 already
