### ISSUE TITLE
IMEI and Baseband Unknown on 20231110 build on MediaTek Devices(and possibly non MediaTek devices as well)

### ISSUE THREAD

**Issue by LordDemecrius83** [boydaihungst/treble_build_derpfest#15]
After flashing the newest build, my SIM is not getting detected anymore

It seems that Derpfest Telephony has killed RIL on MTK devices

**Comment by LordDemecrius83** [comment]
There seems to be a lot of errors relating to telephony

[Uploading ril_dead.log…]()

**Comment by LordDemecrius83** [comment]
`11-10 22:56:46.704 13449 13449 E AndroidRuntime: Process: com.android.phone, PID: 13449
11-10 22:56:46.704 13449 13449 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.android.phone.PhoneApp: java.lang.SecurityException: com.android.phone: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7004)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: Caused by: java.lang.SecurityException: com.android.phone: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3041)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3024)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2966)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5700)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:767)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at com.android.internal.telephony.PhoneConfigurationManager.<init>(PhoneConfigurationManager.java:128)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at com.android.internal.telephony.PhoneConfigurationManager.init(PhoneConfigurationManager.java:99)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at com.android.internal.telephony.PhoneFactory.makeDefaultPhone(PhoneFactory.java:270)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at com.android.internal.telephony.PhoneFactory.makeDefaultPhones(PhoneFactory.java:109)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at com.android.phone.PhoneGlobals.onCreate(PhoneGlobals.java:463)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at com.android.phone.PhoneApp.onCreate(PhoneApp.java:39)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1322)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6999)
11-10 22:56:46.704 13449 13449 E AndroidRuntime: 	... 9 more
11-10 22:56:46.705  1944  1965 W ActivityManager: Process com.android.phone has crashed too many times, killing! Reason: crashed quickly`

**Comment by boydaihungst** [comment]
Mobile network no signal if you do clean flash. To fix this you need to go to Settings > Phh Treble Settings > IMS features > Tap "Install IMS APK for ...". Install ims.apk after it's downloaded > Tap "Create IMS APN" then switch on both "Request IMS network" and "Force the presence of 4G Calling setting"

**Comment by MITRVARUN** [comment]
Okay thanks
