### ISSUE TITLE
IMEI no. Lost in mt6765 device 

### ISSUE THREAD

**Issue by MITRVARUN** [boydaihungst/treble_build_derpfest#17]
When I installed latest 10 November build. Network signals are lost due to IMEI no. Not available after install..

**Comment by LordDemecrius83** [comment]
https://github.com/boydaihungst/treble_build_derpfest/issues/15#issuecomment-1806197287

**Comment by boydaihungst** [comment]
I've written a fix in "known bug" section of release page.
