### ISSUE TITLE
please exFAT sdcard supported

### ISSUE THREAD

**Issue by teerasak** [boydaihungst/treble_build_derpfest#2]
please exFAT sdcard supported. Thanks

**Comment by boydaihungst** [comment]
Does this only happen in derpfast or also in ponces' AOSP?

**Comment by teerasak** [comment]
> Does this only happen in derpfast or also in ponces' AOSP?

Deepest always expat supported include your
" https://sourceforge.net/projects/nubia-6s-pro-pixel-gsi/files/derpfest_android_14/DerpFest_arm64-ab-14.0_10-06-23-10-2023-UNOFFICIAL.img.xz/download"
And evol x never expat supported include your latest version (A14).

Ponse'aosp always exfat supported include latest.(A14)

**Comment by ngocanhtve** [comment]
ExFat is already supported.
