### ISSUE TITLE
Screen recording 

### ISSUE THREAD

**Issue by MITRVARUN** [boydaihungst/treble_build_derpfest#20]
Screen recording not working  phone perform soft reboot.

**Comment by boydaihungst** [comment]
Give me some logs. `adb logcat > log.txt`

**Comment by boydaihungst** [comment]
What is your kernel version?

**Comment by MITRVARUN** [comment]
<form name="codeSnippet" id="codeSnippet" class="container" style="box-sizing: border-box; display: flex; height: calc(var(--vh, 1vh) * 100); padding: 0px; margin: 0px; flex-direction: row-reverse; color: rgb(0, 0, 0); font-family: &quot;Fira Code v2&quot;, monospace; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="main" class="content" style="box-sizing: border-box; flex: 5 1 0%; max-height: 100%; max-width: 100%; overflow-wrap: break-word; height: 860px;"><code name="snippet" spellcheck="false" data-gramm="false" readonly="true" id="snippet" class="textarea" style="box-sizing: border-box; margin: 0px; font-family: &quot;Fira Code v2&quot;, monospace; font-size: 10pt; display: inline-block; outline: transparent solid 0px; background: rgb(0, 0, 0); height: 860px; width: 400px; padding: 0.5em; overflow: auto; color: rgb(238, 238, 238); border: none; resize: none; tab-size: 4; white-space: pre; overflow-wrap: normal; word-break: normal;">

  | time: 1699757022699
-- | --
  | device fp:Infinix/X688B-GL/Infinix-X688B:11/RP1A.200720.011/230324V619:user/release-keys
  | product board:Infinix-X688B
  | derpfest vers:14-Community-Alpha--20231106
  | msg: java.lang.NoSuchMethodError: No direct method <init>(ZZ)V in class Lcom/android/systemui/plugins/ClockConfig; or its super classes (declaration of 'com.android.systemui.plugins.ClockConfig' appears in /system/system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk)
  | stacktrace: java.lang.NoSuchMethodError: No direct method <init>(ZZ)V in class Lcom/android/systemui/plugins/ClockConfig; or its super classes (declaration of 'com.android.systemui.plugins.ClockConfig' appears in /system/system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk)
  | at com.android.systemui.clocks.SimpleClockController$config$2.invoke(SimpleClockController.kt:42)
  | at com.android.systemui.clocks.SimpleClockController$config$2.invoke(SimpleClockController.kt:41)
  | at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
  | at com.android.systemui.clocks.SimpleClockController.getConfig(SimpleClockController.kt:41)
  | at com.android.customization.module.ThemePickerInjector$getClockSettingsViewModelFactory$1.invoke(ThemePickerInjector.kt:11)
  | at com.android.customization.picker.clock.ui.viewmodel.ClockSettingsViewModel$isSliderEnabled$1.invokeSuspend(ClockSettingsViewModel.kt:24)
  | at com.android.customization.picker.clock.ui.viewmodel.ClockSettingsViewModel$isSliderEnabled$1.invoke(ClockSettingsViewModel.kt:20)
  | at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:56)
  | at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
  | at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:245)
  | at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:8)
  | at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:110)
  | at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:24)
  | at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:119)
  | at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:3)
  | at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:7)
  | at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:80)
  | at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:57)
  | at kotlinx.coroutines.channels.BufferedChannel.trySend-JP2dKIU(BufferedChannel.kt:105)
  | at kotlinx.coroutines.channels.ChannelCoroutine.trySend-JP2dKIU(ChannelCoroutine.kt:3)
  | at com.android.customization.picker.clock.data.repository.ClockPickerRepositoryImpl$selectedClock$1.invokeSuspend$send(ClockPickerRepositoryImpl.kt:105)
  | at com.android.customization.picker.clock.data.repository.ClockPickerRepositoryImpl$selectedClock$1.invokeSuspend(ClockPickerRepositoryImpl.kt:43)
  | at com.android.customization.picker.clock.data.repository.ClockPickerRepositoryImpl$selectedClock$1.invoke(ClockPickerRepositoryImpl.kt:13)
  | at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:62)
  | at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:33)
  | at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:8)
  | at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:110)
  | at android.os.Handler.handleCallback(Handler.java:958)
  | at android.os.Handler.dispatchMessage(Handler.java:99)
  | at android.os.Looper.loopOnce(Looper.java:205)
  | at android.os.Looper.loop(Looper.java:294)
  | at android.app.ActivityThread.main(ActivityThread.java:8178)
  | at java.lang.reflect.Method.invoke(Native Method)
  | at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
  | Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b0a0f9, Dispatchers.Main.immediate]
  |  
  |  

</code></div></form><footer style="box-sizing: border-box; color: rgb(170, 170, 170); font-size: 0.8em; display: flex; flex-direction: row; align-items: center; justify-content: flex-end; min-height: 30px; height: 5vh; position: absolute; bottom: 0px; left: 0px; width: calc(var(--vw, 1vw) * 100); background: rgba(229, 42, 87, 0.024); backdrop-filter: blur(5px); padding-right: 2em; padding-left: 2em; font-family: &quot;Fira Code v2&quot;, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="footer-keybindings" style="box-sizing: border-box; margin-right: auto; color: rgb(238, 238, 238);"><a href="https://bin.kv2.dev/" id="newButton" class="submit" style="box-sizing: border-box; text-align: left; text-decoration: none; color: rgb(238, 238, 238); background: transparent; border: none; font-family: &quot;Fira Code v2&quot;, monospace; padding: 10px;">New Snippet</a><span> </span><span> </span><button type="submit" formaction="https://bin.kv2.dev/fork" formenctype="application/x-www-form-urlencoded" formmethod="post" form="codeSnippet" id="actionButton" class="submit" style="box-sizing: border-box; text-align: left; text-decoration: none; color: rgb(238, 238, 238); background: transparent; border: none; font-family: &quot;Fira Code v2&quot;, monospace; padding: 10px;">Fork</button><span> </span></div><a href="https://github.com/mojurasu/memocho" target="blank" rel="noopener" id="name-label" style="box-sizing: border-box; color: rgb(229, 42, 87); text-decoration: none; padding: 10px;"> Memochō</a></footer>time: 1699757022699
device fp:Infinix/X688B-GL/Infinix-X688B:11/RP1A.200720.011/230324V619:user/release-keys
product board:Infinix-X688B
derpfest vers:14-Community-Alpha--20231106
msg: java.lang.NoSuchMethodError: No direct method <init>(ZZ)V in class Lcom/android/systemui/plugins/ClockConfig; or its super classes (declaration of 'com.android.systemui.plugins.ClockConfig' appears in /system/system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk)
stacktrace: java.lang.NoSuchMethodError: No direct method <init>(ZZ)V in class Lcom/android/systemui/plugins/ClockConfig; or its super classes (declaration of 'com.android.systemui.plugins.ClockConfig' appears in /system/system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk)
	at com.android.systemui.clocks.SimpleClockController$config$2.invoke(SimpleClockController.kt:42)
	at com.android.systemui.clocks.SimpleClockController$config$2.invoke(SimpleClockController.kt:41)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.android.systemui.clocks.SimpleClockController.getConfig(SimpleClockController.kt:41)
	at com.android.customization.module.ThemePickerInjector$getClockSettingsViewModelFactory$1.invoke(ThemePickerInjector.kt:11)
	at com.android.customization.picker.clock.ui.viewmodel.ClockSettingsViewModel$isSliderEnabled$1.invokeSuspend(ClockSettingsViewModel.kt:24)
	at com.android.customization.picker.clock.ui.viewmodel.ClockSettingsViewModel$isSliderEnabled$1.invoke(ClockSettingsViewModel.kt:20)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:56)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:245)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:8)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:110)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:24)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:119)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:3)
	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:7)
	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:80)
	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:57)
	at kotlinx.coroutines.channels.BufferedChannel.trySend-JP2dKIU(BufferedChannel.kt:105)
	at kotlinx.coroutines.channels.ChannelCoroutine.trySend-JP2dKIU(ChannelCoroutine.kt:3)
	at com.android.customization.picker.clock.data.repository.ClockPickerRepositoryImpl$selectedClock$1.invokeSuspend$send(ClockPickerRepositoryImpl.kt:105)
	at com.android.customization.picker.clock.data.repository.ClockPickerRepositoryImpl$selectedClock$1.invokeSuspend(ClockPickerRepositoryImpl.kt:43)
	at com.android.customization.picker.clock.data.repository.ClockPickerRepositoryImpl$selectedClock$1.invoke(ClockPickerRepositoryImpl.kt:13)
	at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:62)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:8)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:110)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b0a0f9, Dispatchers.Main.immediate]
[New Snippet](https://bin.kv2.dev/)  Fork 
[ Memochō](https://github.com/mojurasu/memocho)

**Comment by boydaihungst** [comment]
Next time, please save it to a file and upload in here. 🤦

**Comment by boydaihungst** [comment]
This is bug about clock? Not screen recorder.

**Comment by MITRVARUN** [comment]
[log.txt](https://github.com/boydaihungst/treble_build_derpfest/files/13327190/log.txt)

**Comment by MITRVARUN** [comment]
[Uploading logs 2.txt…]()

**Comment by boydaihungst** [comment]
Check the file again.

**Comment by MITRVARUN** [comment]
[logs 2.txt](https://github.com/boydaihungst/treble_build_derpfest/files/13327233/logs.2.txt)

**Comment by boydaihungst** [comment]
Does this bug only happen with DerpFest or with all GSI?

**Comment by MITRVARUN** [comment]
I again flash drepfest and all things are working fine but wallpaper clock settings app has bugs. 


Screen recording is also working fine thanks

**Comment by MITRVARUN** [comment]
> Does this bug only happen with DerpFest or with all GSI?

Drepfest is working fine when I flash it again but wallpaper clock settings are not working properly.. thanks boydaihungst

**Comment by boydaihungst** [comment]
Ok I will close this issue.
