### ISSUE TITLE
Crashes when trying to set up a fingerprint

### ISSUE THREAD

**Issue by rama982** [boydaihungst/treble_build_derpfest#25]
Opening Pixel Imprint crash, log attached

[logcat2.txt](https://github.com/boydaihungst/treble_build_derpfest/files/13342961/logcat2.txt)

**Comment by rama982** [comment]
more info
build: v2023.11.13
device: infinix note 30 pro with mediatek helio g99

**Comment by boydaihungst** [comment]
just to be clear, does fingerprint work on other builds? ponces or td. I noticed they updated some part of fingerprint enrolling. [This commit](https://github.com/DerpFest-AOSP/packages_apps_Settings/commit/f90d1cd0ffeab035831d6df4224ed222e3ebd88d).  I will make a new build in 2-3 days and will ping you to test.

**Comment by rama982** [comment]
Yes, and just now I used app manager and launch pixel imprint activity to set fingerprint directly and it works 😂

**Comment by boydaihungst** [comment]
One more thing I need you to do: And run this command `adb root && adb shell "dumpsys fingerprint" > log.txt`.
![Screenshot_20231114-074501_Settings](https://github.com/boydaihungst/treble_build_derpfest/assets/38396158/1ec76510-f42a-4cb4-8df5-bd2343ab79b1)

**Comment by rama982** [comment]
here

[log.txt](https://github.com/boydaihungst/treble_build_derpfest/files/13343363/log.txt)

**Comment by boydaihungst** [comment]
@rama982 Please check this release and report to me if it is fixed in your device
https://github.com/boydaihungst/treble_build_derpfest/releases/tag/v2023.11.16

**Comment by rama982** [comment]
> @rama982 Please check this release and report to me if it is fixed in your device https://github.com/boydaihungst/treble_build_derpfest/releases/tag/v2023.11.16

yes it fixed on my device no more fc thanks.
