### ISSUE TITLE
Missing DerpFest entry in Settings app 

### ISSUE THREAD

**Issue by lyricalsoul** [boydaihungst/treble_build_derpfest#3]
Normally, you'd expect for a DerpFest ROM to have a DerpSpace entry in the Settings app. However, for whatever reason, it doesn't show up in the latest version of the GSI build.

![Screenshot_20231104-010643](https://github.com/boydaihungst/treble_build_derpfest/assets/95383663/ceca8c28-75fa-4ab1-b6f3-c95720a0ccb5)

DF Version: `14-Community-Alpha--20231102`

**Comment by boydaihungst** [comment]
It's in the initial stage. It's not implemented in Android 14 yet.
