### ISSUE TITLE
battery style crashes

### ISSUE THREAD

**Issue by rocwaj** [boydaihungst/treble_build_derpfest#30]
Some battery style settings corrupt settings and aren't applied. (settings in A13 builds worked fine)

**Comment by boydaihungst** [comment]
Thanks for reporting. Derp space isn't fully implemented yet, so bug are expecting. 😅

**Comment by boydaihungst** [comment]
fixed with latest build. https://github.com/boydaihungst/treble_build_derpfest/releases/tag/v2023.11.19
