### ISSUE TITLE
Feature Request: Replace AOSP Gallery3d with Google Photos on Mini gapps build

### ISSUE THREAD

**Issue by LordDemecrius83** [boydaihungst/treble_build_derpfest#35]
AOSP Gallery3D doesn't detect any media unless you manually allow it which could be confusing to new users

**Comment by boydaihungst** [comment]
It will take ~150 MB. Most of the apps that were removed from the mini-build can be installed through GG Play Store. There is nothing different.

**Comment by LordDemecrius83** [comment]
> It will take ~150 MB. Most of the apps that were removed from the mini-build can be installed through GG Play Store. There is nothing different.

Oh, ok

I thought gphotos would be at 80mb at best

**Comment by boydaihungst** [comment]
https://gitlab.com/DerpFest/vendor_gms/-/blob/14/common/proprietary/product/app/Photos/Photos.apk?ref_type=heads
It actually ~130Mib
