### ISSUE TITLE
Fingerprint Setup crashes settings on Mini gapps(not sure about full build)

### ISSUE THREAD

**Issue by LordDemecrius83** [boydaihungst/treble_build_derpfest#36]
Can't enroll fingerprint on a fresh install due to settings app crashing when trying to add fingerprint

to reproduce
Open settings>Security and Privacy>Device Unlock>Fingerprint then settings will crash

**Comment by boydaihungst** [comment]
What build are you using? This shouble be fixed in the latest build (20231117)

**Comment by LordDemecrius83** [comment]
> What build are you using? This shouble be fixed in the latest build (20231117)

derpfest_arm64-ab-mini-unofficial-20231117.img

**Comment by boydaihungst** [comment]
Ok gather log and upload it here.

**Comment by LordDemecrius83** [comment]
> Ok gather log and upload it here.

https://bin.kv2.dev/~6558fc5d5de7ed6bfdba5423

I just used the copy crash log url feature because my internet sucks and uploading fails

**Comment by boydaihungst** [comment]
What is your device? Is it using side finferprint or on display fingerprint?

**Comment by boydaihungst** [comment]
Please test the latest build. https://github.com/boydaihungst/treble_build_derpfest/releases/tag/v2023.11.19

**Comment by boydaihungst** [comment]
Please confirm whether thid bug is fixed or not in the latest build.
 https://github.com/boydaihungst/treble_build_derpfest/releases/tag/v2023.11.19

**Comment by LordDemecrius83** [comment]
Downloading...
Will report back later

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by LordDemecrius83** [comment]
> Please confirm whether thid bug is fixed or not in the latest build. https://github.com/boydaihungst/treble_build_derpfest/releases/tag/v2023.11.19

Fixed on 20231119
