### ISSUE TITLE
add adaptive brightness and e-sim support 

### ISSUE THREAD

**Issue by omar-ly** [boydaihungst/treble_build_derpfest#37]
i struggled to install this GSI on my SCG02 Samsung galaxy s20+, but it's all worth it, the SCG02  doesn't have e-sim settings in the main rom, but i installed the US Version and it appeared to work, and also the gsi missing the adaptive brightness

**Comment by boydaihungst** [comment]
Sorry currently it doesn't support esim.
Adaptive brightness need custom overlay. you have to do it yourself and merge to [this repo](https://github.com/TrebleDroid/vendor_hardware_overlay)

How to make overlay: 
https://github.com/phhusson/treble_experimentations/wiki/How-to-create-an-overlay%3F
