### ISSUE TITLE
pixel launcher force stop

### ISSUE THREAD

**Issue by jangsangin** [boydaihungst/treble_build_derpfest#4]
not work pixel launcher.

**Comment by boydaihungst** [comment]
Pixel launcher is used for "recent apps". So you just can't disable or force close it. 
This is "recent apps":
![Screenshot_20231107-162413_Pixel_Launcher](https://github.com/boydaihungst/treble_build_derpfest/assets/38396158/3ff1a393-f1e5-48fc-9e7d-66b972eab51c)
