### ISSUE TITLE
pixel launcher force stop.

### ISSUE THREAD

**Issue by jangsangin** [boydaihungst/treble_build_derpfest#5]
occur alram  "pixel laucher stopping."
so i install other launcher. but occur again

**Comment by boydaihungst** [comment]
Do clean flash.

**Comment by LordDemecrius83** [comment]
Workaround for Pixel Launcher black screen on subsequent boots

Go to Settings using the QS Panel>Apps>Default Apps then press the cog next to Pixel Launcher then disable Swipe to access google app then reboot

**Comment by LordDemecrius83** [comment]
> `fastboot -w` after flash system

Swipe to access Google app seems to be the culprit since Pixel Launcher stops working for me after the first boot until I did the steps above

**Comment by jangsangin** [comment]
> Workaround for Pixel Launcher black screen on subsequent boots
> 
> Go to Settings using the QS Panel>Apps>Default Apps then press the cog next to Pixel Launcher then disable Swipe to access google app then reboot

not work your method. i cant disable
