### ISSUE TITLE
Please do a mini vndklite build with selinux allowing phh-su

### ISSUE THREAD

**Issue by Skorpion96** [boydaihungst/treble_build_derpfest#6]
I tried to add phh-su to your derpfest_arm64-ab-mini-vndklite-unofficial-20231107 build but selinux is preventing to run su at boot, and so superuser doesn't work. Could you please edit selinux policies to allow it? If you are asking why i want it, it's because i can't use magisk (as i'm on locked bootloader), i'm using an engineering firmware which doesn't check system and vendor. Or if you want you can tell me what to edit in policies to allow su to run at boot

**Comment by boydaihungst** [comment]
Try this tool. https://github.com/ponces/treble_adapter

**Comment by Skorpion96** [comment]
It worked, many thanks

**Comment by Skorpion96** [comment]
[logcat.log](https://github.com/boydaihungst/treble_build_derpfest/files/13283894/logcat.log)
Sorry for disturbing again, i have limited connectivity after a while, changing dns, ip or disconnecting and reconnecting doesn't fix the issue, only way to fix iit is to reboot. I did some log if you want to have a look and hopefully fix it on a new build. I'm on unisoc sc9863a

**Comment by boydaihungst** [comment]
Go to wifi > select wifi setting (next to wifi name) > network usages> unmetered. Or check your router configuration.
![Screenshot_20231108-002019_Settings](https://github.com/boydaihungst/treble_build_derpfest/assets/38396158/7fd6e060-451e-4ab7-8a16-179f6b92da91)

**Comment by Skorpion96** [comment]
Well I tried to set network as unmetered but it still doesn't work, btw when network is setting as limited system soft reboots. I'm sure my router is fine, I use many other phones/pcs and even on this same device with stock or other gsis internet works fine, so I pretty much think that this issue is only related to your gsi. Maybe it's because android 14 is too new, I don't know honestly

**Comment by boydaihungst** [comment]
Have you tried Trebledroid a14? This custom build is partly based on that. Maybe it's a hardware compatibility bug?

**Comment by Skorpion96** [comment]
Yes, I tried trebledroid android 14, also leos I  which is android 14, both of them worked fine

**Comment by boydaihungst** [comment]
What is your kernel version?

**Comment by Skorpion96** [comment]
My kernel version is 4.4.147+

**Comment by boydaihungst** [comment]
Unfortunately. https://github.com/DerpFest-AOSP/system_bpf/commit/0b4410a004320c55b0d52411534f5ba40e11452d#diff-8bdd1b7e8d8ed2ee94e3b9b0bfa7cfe5ebe4685e137a151ddf6fd98dae626f35R694

![Screenshot_20231108-165534_Firefox_Nightly](https://github.com/boydaihungst/treble_build_derpfest/assets/38396158/56c414fd-7964-42c2-8b88-a7c5a65e3d37)
