### ISSUE TITLE
Banking app not working on the Nov 7, 2023 alpha release

### ISSUE THREAD

**Issue by tutu-rulianda** [boydaihungst/treble_build_derpfest#7]
Hello,

First of all, many thanks for you by providing us with the latest and greatest Android 14 custom ROM. This time I have got an issue with a banking app using the Derpfest Nov 7, 2023. alpha release. However, safetynet check has no issue and passes the verification test.

I have patched it using Magisk Modules such as Zygisk SU Kernel, LSPosed, Shamiko, and Play Integrity. It worked on the Nov 2, 2023 alpha release. But on the Nov 7, 2023 alpha release with the same configuration of Magisk Modules, the banking app is no longer working.

Thanks and Regards,
Ruli

![Screenshot_20231107-215700_Pixel_Launcher](https://github.com/boydaihungst/treble_build_derpfest/assets/79007866/24eb016d-e695-4b33-a6ef-70927cb632f6)

**Comment by boydaihungst** [comment]
You should ask in magisk group. I didn't use your bank app so can't help. My advice is clear app data, reinstall or use hide my app list blacklist to hide all apps related to root.

**Comment by tutu-rulianda** [comment]
Thank you for your advice.
