### ISSUE TITLE
The clock writing is slightly cut off on the left side.

### ISSUE THREAD

**Issue by tutu-rulianda** [boydaihungst/treble_build_derpfest#8]
Hello,

This is a bit of a cosmetic issue. The clock is written slightly to the top of the status bar. Please lower the clock slightly down in the status bar, so that the writing is not cut off on the left side.

Thank you and Greetings,
Ruli

**Comment by boydaihungst** [comment]
Can you send me a screenshot?

**Comment by boydaihungst** [comment]
The saw screenshot from your previous issue. You can set offset/padding/margin in phh setting > misc > set rounded corners diameter.
