### ISSUE TITLE
settings FC when trying to change sounds on mini build

### ISSUE THREAD

**Issue by LordDemecrius83** [boydaihungst/treble_build_derpfest#9]
Trying to change ringtones/notifications/alarm sound will cause Settings app to fc(at least on mini build)

**Comment by boydaihungst** [comment]
Thanks for reporting. Will be fixed in the release.

**Comment by boydaihungst** [comment]
Fixed in release [v2023.11.10](https://github.com/boydaihungst/treble_build_derpfest/releases/tag/v2023.11.10)
